name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ghidra_version:
        description: 'Specify the Ghidra version(s) you want to build for (e.g. "latest", "11.0")'
        required: true
        default: '"latest"'
  schedule:
    - cron: '0 0 1 * *' # Monthly

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghidra: ${{ fromJSON(format('[{0}]', inputs.ghidra_version || '"latest", "11.2.1", "11.1.2","11.1.1","11.1","11.0.3","11.0.2","11.0.1","11.0"')) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Setup Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v2.0.3
      with:
        version: ${{ matrix.ghidra }}

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build
      run: gradle buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ghidracord_${{ matrix.ghidra }}
        path: dist/*
