name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghidra:
          - "latest"
          - "11.1.2"
          - "11.1.1"
          - "11.1"
          - "11.0.3"
          - "11.0.2"
          - "11.0.1"
          - "11.0"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Setup Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v2.0.3
      with:
        version: ${{ matrix.ghidra }}

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build
      run: gradle buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ghidracord_${{ matrix.ghidra }}
        path: dist/*
